CREATE TABLE ORDERS
(
	ID_ORDER SERIAL NOT NULL,
	REGISTRATION_DATE DATE NOT NULL,
	SUMM_ORDER MONEY,
	DATE_OF_ISSUE DATE NOT NULL,
	NAME_CLIENT TEXT NOT NULL,
	PHONE_CLIENT TEXT NOT NULL,
	PRIMARY KEY(ID_ORDER)
)

CREATE TABLE PRODUCTION
(
	ID_PRODUCT SERIAL NOT NULL,
	NAME_PRODUCT TEXT NOT NULL,
	WEIGHT INTEGER NOT NULL,
	PRIMARY KEY (ID_PRODUCT)
)

CREATE TABLE  EMPLOEE
(
	ID_EMPLOEE SERIAL NOT NULL,
	PHONE_NUMBER TEXT NOT NULL,
	LOGIN TEXT UNIQUE NOT NULL,
	NAME_EMPLOEE TEXT NOT NULL,
	SECONDNAME_EMPLOEE TEXT NOT NULL,
	SURNAME_EMPLOEE TEXT,
	PASSWORD_EMPLOEE TEXT,
	PRIMARY KEY(ID_EMPLOEE)
)

CREATE TABLE PAYMENT
(
	ID_PAYMENT SERIAL NOT NULL,
	DATE_PAYMENT DATE NOT NULL,
	SUMM_PAYMENT MONEY,
	PRIMARY KEY(ID_PAYMENT),
	FOREIGN KEY(ID_PAYMENT) REFERENCES EMPLOEE(ID_EMPLOEE),
	FOREIGN KEY(ID_PAYMENT) REFERENCES ORDERS(ID_ORDER)
	
)

CREATE TABLE ORDER_PRODUCTION
(
	ID_ORDER_PRODUCTION SERIAL NOT NULL,
	PRIMARY KEY(ID_ORDER_PRODUCTION),
	FOREIGN KEY(ID_ORDER_PRODUCTION) REFERENCES ORDERS(ID_ORDER),
	FOREIGN KEY(ID_ORDER_PRODUCTION) REFERENCES PRODUCTION(ID_PRODUCT)
)	
